---
    config:
        theme: 'default'
---
mindmap
  root((HTTP Working))
    Client
        Browser
        Mobile App
        IoT Device
    Server
        Web Server
        Application Server
        Database Server
    Networking
        TCP/IP & Ports
        DNS
        HTTPS (TLS/SSL)
    Request
        Method (GET, POST, PUT, DELETE)
        URL & Query Params
        Headers (Authorization, Content-Type, Accept, Cookies)
        Body (JSON, Form Data, Binary)
    Response
        Status Codes (2xx, 3xx, 4xx, 5xx)
        Headers (Content-Type, Set-Cookie, Cache-Control)
        Body (HTML, JSON, Media)
    Media Types (MIME)
        Text (html, plain)
        Application (json, xml)
        Image/Audio/Video
    Sessions & Authentication
        Cookies (Session, Persistent)
        Tokens (JWT, OAuth)
        HTTP Auth (Basic, Bearer)
    Caching
        Cache-Control, ETag
    %% Advanced Concepts
    %%     HTTP/1.1 vs HTTP/2
    %%     WebSockets
    %%     Content Negotiation
